"""empty message

Revision ID: a794b9773b37
Revises: 
Create Date: 2024-11-13 16:24:43.109250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a794b9773b37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('dynatrace_environment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_name', sa.String(length=150), nullable=False),
    sa.Column('environment_id', sa.String(length=100), nullable=False),
    sa.Column('environment_url', sa.String(length=200), nullable=False),
    sa.Column('environment_api_token', sa.String(length=200), nullable=False),
    sa.Column('environment_paas_token', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_managed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id')
    )
    op.create_table('section_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', 'section_id', name='unique_user_section')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('section_id', sa.String(length=50), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_vm_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aks_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('azure_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_aks_cluster_user'),
    sa.ForeignKeyConstraint(['vm_id'], ['vms.id'], name='fk_aks_cluster_vm'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('frontend_service', sa.String(length=100), nullable=False),
    sa.Column('frontend_ip', sa.String(length=100), nullable=True),
    sa.Column('frontend_port', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['aks_clusters.id'], name='fk_deployment_cluster'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments')
    op.drop_table('aks_clusters')
    op.drop_table('vms')
    op.drop_table('user_progress')
    op.drop_table('section_completion')
    op.drop_table('dynatrace_environment')
    op.drop_table('user')
    # ### end Alembic commands ###
